DROP TABLE IF EXISTS EquipesJoueurs;
DROP TABLE IF EXISTS Resultat;
DROP TABLE IF EXISTS Joueurs;
DROP TABLE IF EXISTS Epreuve;
DROP TABLE IF EXISTS Equipe;
DROP TABLE IF EXISTS Rencontres;
DROP TABLE IF EXISTS Sport;

CREATE TABLE Joueurs(
  id SERIAL PRIMARY KEY,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  age INTEGER NOT NULL
);

CREATE TABLE Rencontres (
  id SERIAL PRIMARY KEY,
  date DATE NOT NULL
);

CREATE TABLE Equipe (
  id SERIAL PRIMARY KEY,
  pays VARCHAR(30) NOT NULL
);


CREATE TABLE EquipesJoueurs (
  id SERIAL PRIMARY KEY,
  joueur INTEGER NOT NULL REFERENCES Joueurs (id) ON DELETE CASCADE ON UPDATE CASCADE,
  equipe INTEGER NOT NULL REFERENCES Equipe (id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Sport (
  id SERIAL PRIMARY KEY,
  nom VARCHAR(50)
);


CREATE TABLE Epreuve (
  id SERIAL PRIMARY KEY,
  sexe CHAR(1),
  nom TEXT NOT NULL,
  lieu TEXT NOT NULL,
  sport INTEGER NOT NULL REFERENCES Sport (id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Resultat (
  id SERIAL PRIMARY KEY,
  Equipe INTEGER REFERENCES Equipe (id) ON DELETE CASCADE ON UPDATE CASCADE,
  Epreuve INTEGER REFERENCES Epreuve (id) ON DELETE CASCADE ON UPDATE CASCADE,
  Rencontres INTEGER REFERENCES Rencontres (id) ON DELETE CASCADE ON UPDATE CASCADE,
  Position INTEGER,
  Temps TIME,
  Points INTEGER
);
